#!/usr/bin/env python

import argparse

import yaml

from wade import chain


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='kv config loader')
    parser.add_argument('--conf', type=str, required=True, help='config')

    args = parser.parse_args()

    conf = yaml.load(open(args.conf, 'r').read())

    nodes = conf['nodes']
    c = chain.Client(conf)
    print c.special_op(None, '.RELOAD_CONFIG', { 'conf': conf }, 'configure-kv')
