#!/usr/bin/env python

import argparse

import yaml

from wade import chorus


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='kv config loader')
    parser.add_argument('--conf', type=str, required=True, help='config')

    args = parser.parse_args()

    conf = yaml.load(open(args.conf, 'r').read())

    nodes = conf['nodes']
    c = chorus.Client(nodes)
    for node_id in nodes.keys():
        print node_id, c.reqrep(node_id,
                                {
                                    'obj_id': None,
                                    'obj_seq': None,
                                    'op': '.RELOAD_CONF',
                                    'args': { 'conf': conf },
                                    'debug_tag': 'configure-kv',
                                })
